// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectShadowsocks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectShadowsocks'](arg1, arg2, arg3);
}

export function DumpLogContent(arg1) {
  return window['go']['main']['App']['DumpLogContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDirectoryEntries() {
  return window['go']['main']['App']['ListDirectoryEntries']();
}

export function ListDirectoryEntriesForPath(arg1) {
  return window['go']['main']['App']['ListDirectoryEntriesForPath'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
