// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectShadowsocks(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DumpLogContent(arg1:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function UploadFile(arg1:string):Promise<void>;
